# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'leoUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_leoGui(object):
    def setupUi(self, leoGui):
        leoGui.setObjectName("leoGui")
        leoGui.resize(1318, 818)
        self.centralwidget = QtWidgets.QWidget(leoGui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-120, 0, 1461, 821))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 230, 811, 621))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("New folder/Glow Matrix - Animated.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-110, 200, 871, 641))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("New folder/download-removebg.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, -60, 551, 231))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("New folder/initiating.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(550, -120, 771, 341))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("New folder/loading_1.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 100, 801, 141))
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 120, 231, 61))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size: 20px;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(270, 120, 231, 61))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size: 20px;\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(860, 620, 241, 181))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("New folder/Picsart_23-08-06_16-30-54-713.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(910, 640, 151, 61))
        font = QtGui.QFont()
        font.setFamily("EngraversGothic BT")
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background:transparent;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 720, 151, 61))
        font = QtGui.QFont()
        font.setFamily("EngraversGothic BT")
        font.setPointSize(22)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background:transparent;\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1080, 660, 201, 91))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../../../Downloads/Picsart_23-08-06_16-46-57-483.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1110, 680, 151, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet("background:transparent;\n")
        leoGui.setCentralWidget(self.centralwidget)

        self.retranslateUi(leoGui)
        QtCore.QMetaObject.connectSlotsByName(leoGui)

    def retranslateUi(self, leoGui):
        _translate = QtCore.QCoreApplication.translate
        leoGui.setWindowTitle(_translate("leoGui", "MainWindow"))
        self.label.setText(_translate("leoGui", "TextLabel"))
        self.label_6.setText(_translate("leoGui", "TextLabel"))
        self.pushButton_3.setText(_translate("leoGui", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    leoGui = QtWidgets.QMainWindow()
    ui = Ui_leoGui()
    ui.setupUi(leoGui)
    leoGui.show()
    sys.exit(app.exec_())
